const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const TOML = require("@iarna/toml");
const { Store } = require("../core/store.cjs");
const { ConfigManager, atomic } = require("../core/config.cjs");
const { HarnessManager } = require("../core/harnesses.cjs");
const { ProxyConfig } = require("../core/proxy-config.cjs");
const { Connections } = require("../core/connections.cjs");
const { InjectionFiles } = require("../core/injection-files.cjs");
const { Router } = require("../core/router.cjs");
const crypt = { isEncryptionAvailable: () => true, encryptString: s => Buffer.from(s), decryptString: b => b.toString() };
function fixture(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ass-accountless-")), data = path.join(dir, "data"), home = path.join(dir, "home"), codex = path.join(home, ".codex");
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const baseline = 'model = "gpt-original"\nmodel_reasoning_effort = "high"\n[features]\nkeep = true\n';
  atomic(path.join(codex, "config.toml"), baseline);
  atomic(path.join(codex, "auth.json"), '{"tokens":{"access_token":"synthetic-original"}}');
  const store = new Store(data, codex, crypt);
  store.updateProvider({ id: "relay", baseUrl: "https://relay.example/v1", apiKey: "synthetic-provider", models: [{ model: "test-claude", wireApi: "anthropic" }, { model: "test-chat", wireApi: "openai-chat" }] });
  const injections = new InjectionFiles(data), config = new ConfigManager(codex, data);
  let connections;
  const manager = new HarnessManager(data, () => store.state, store.officialModels, codex, { home, env: {}, launchEnv: { PATH: "" }, injections, isConnected: id => connections.allow(id) });
  const proxy = new ProxyConfig(data, crypt, manager, store, config);
  manager.options.proxyConfig = proxy;
  const calls = [];
  const router = new Router({ getState: id => proxy.routingState(id), allowClient: id => connections.allow(id), fetchUpstream: async (url, init) => {
    calls.push({ url, init }); return new Response(JSON.stringify({ type: "message", content: [{ type: "text", text: "OK" }] }), { status: 200 });
  } });
  t.after(() => router.stop());
  connections = new Connections({ dataDir: data, router, config, proxyConfig: proxy, injections, port: 0,
    processes: { refresh: async () => {}, snapshot: () => ({ sessions: [] }) } });
  const apply = async (id, mode) => connections.apply({ ticket: (await connections.preview(id, true, false, mode)).ticket, mode: "safe", acknowledged: true });
  return { dir, data, codex, baseline, store, config, manager, proxy, connections, router, calls, apply };
}
test("accountless requires an applied nonempty injection; drafts and other clients cannot activate it", async t => {
  const f = fixture(t);
  await assert.rejects(f.apply("codex", true), /请先开启/);
  await f.apply("codex");
  f.manager.setInjection("codex", { excludedProviders: ["relay"] });
  await assert.rejects(f.apply("codex", true), /尚未同步/);
  await f.apply("codex");
  await assert.rejects(f.apply("codex", true), /至少一个/);
  await assert.rejects(f.apply("pi", true), /请先开启/);
});
test("a fresh Codex home can inject and enter accountless mode without creating auth.json", async t => {
  const f = fixture(t);
  fs.unlinkSync(path.join(f.codex, "config.toml")); fs.unlinkSync(path.join(f.codex, "auth.json"));
  await f.apply("codex"); await f.apply("codex", true);
  assert.equal(f.proxy.status("codex", true).applied, true);
  assert.ok(!fs.existsSync(path.join(f.codex, "auth.json")));
});
test("desktop mode preserves OAuth bytes, restores native default, and survives restart with its local credential", async t => {
  const f = fixture(t), auth = fs.readFileSync(path.join(f.codex, "auth.json"));
  await f.apply("codex"); await f.apply("codex", true);
  const parsed = TOML.parse(fs.readFileSync(f.config.file, "utf8")), token = f.proxy.clients.codex.localToken;
  assert.equal(parsed.model_providers.ass_router.requires_openai_auth, false);
  assert.equal(parsed.model_providers.ass_router.experimental_bearer_token, token);
  assert.match(parsed.model, /^relay::/);
  assert.ok(JSON.parse(fs.readFileSync(f.config.catalog)).models.every(m => m.slug.startsWith("relay::")));
  assert.deepEqual(fs.readFileSync(path.join(f.codex, "auth.json")), auth);
  const reloaded = new ProxyConfig(f.data, crypt, f.manager, f.store, f.config);
  assert.equal(reloaded.clients.codex.localToken, token); assert.equal(reloaded.status("codex", true).applied, true);
  assert.equal(f.connections.snapshot().clients.codex.accountless, true);
  assert.ok(!JSON.stringify(f.connections.snapshot()).includes(token));
  await f.apply("codex", false);
  const restored = TOML.parse(fs.readFileSync(f.config.file, "utf8"));
  assert.equal(restored.model, "gpt-original"); assert.equal(restored.model_reasoning_effort, "high");
  assert.equal(restored.model_providers.ass_router.requires_openai_auth, true);
  assert.equal(restored.model_providers.ass_router.experimental_bearer_token, undefined);
  assert.deepEqual(fs.readFileSync(path.join(f.codex, "auth.json")), auth);
});
test("Claude has a credential-isolated home, only injected model choices, no account selection and no permission bypass", async t => {
  const f = fixture(t); await f.apply("claude"); await f.apply("claude", true);
  const plan = f.manager.accountlessPlan("claude", "ephemeral-token"); f.manager.materialize(plan);
  const settings = JSON.parse(fs.readFileSync(path.join(plan.dir, "settings.json")));
  assert.deepEqual(settings.availableModels, ["relay::test-claude", "relay::test-chat"]);
  assert.equal(settings.enforceAvailableModels, true); assert.equal(settings.modelPicker.replaceBuiltInOptions, true);
  assert.equal(plan.env.ANTHROPIC_AUTH_TOKEN, f.proxy.clients.claude.localToken);
  assert.equal(plan.env.CLAUDE_CODE_OAUTH_TOKEN, undefined);
  assert.equal(plan.env.ANTHROPIC_API_KEY, undefined);
  assert.ok(!plan.args.includes("--dangerously-skip-permissions"));
  assert.ok(!fs.existsSync(path.join(plan.dir, ".credentials.json")));
  assert.deepEqual(f.manager.state.selected, {});
  assert.throws(() => f.manager.plan("claude", "anything"), /无账号启动已开启/);
});
test("in-flight requests block a mode change and configuration changes invalidate confirmation", async t => {
  const f = fixture(t); await f.apply("codex");
  const p = await f.connections.preview("codex", true, false, true);
  const active = f.router.clientActive; f.router.clientActive = () => 1;
  await assert.rejects(f.connections.apply({ ticket: p.ticket, mode: "safe", acknowledged: true }), /请求正在进行/);
  assert.equal(f.proxy.clients.codex.accountless, undefined); f.router.clientActive = active;
  const next = await f.connections.preview("codex", true, false, true);
  f.manager.setInjection("codex", { excludedProviders: ["relay"] });
  await assert.rejects(f.connections.apply({ ticket: next.ticket, mode: "safe", acknowledged: true }), /已变化/);
});
test("accountless router rejects OAuth, non-injected and subscription models before network access; discovery needs its own credential", async t => {
  const f = fixture(t); await f.apply("codex"); await f.apply("codex", true); await f.apply("claude"); await f.apply("claude", true);
  const base = `http://127.0.0.1:${f.router.port}`;
  const send = (client, token, model) => fetch(base + `/clients/${client}/v1/responses`, { method: "POST", headers: { authorization: "Bearer " + token }, body: JSON.stringify({ model, input: "OK" }) });
  assert.equal((await send("codex", "synthetic-oauth", "relay::test-chat")).status, 401);
  assert.equal((await send("codex", f.proxy.clients.codex.localToken, "gpt-official")).status, 403);
  assert.equal((await send("codex", f.proxy.clients.codex.localToken, "foreign::model")).status, 404);
  assert.equal(f.calls.length, 0);
  const discovery = token => fetch(base + "/clients/claude/models/v1/models", { headers: { authorization: "Bearer " + token } });
  assert.equal((await discovery(f.proxy.clients.codex.localToken)).status, 401);
  const models = await (await discovery(f.proxy.clients.claude.localToken)).json();
  assert.deepEqual(models.data.map(m => m.id), ["relay::test-claude", "relay::test-chat"]);
  assert.equal(models.has_more, false); assert.equal(f.calls.length, 0);
});
