const { test } = require("node:test");
const assert = require("node:assert/strict");
test("theme spring preserves live position and velocity through reversal, dragging and cancellation", async () => {
  const { themeMotion, dragPosition } = await import("../src/theme-motion.mjs");
  let time = 0, callback = null;
  const frames = [], clock = { now: () => time, request: (fn) => { callback = fn; return 1; }, cancel: () => { callback = null; } };
  const m = themeMotion(0, (p, x) => frames.push({ p, x }), clock);
  const advance = () => { const tick = callback; callback = null; time += 16; tick?.(time); };
  m.settle(1); advance(); advance(); advance();
  const previous = m.position, velocity = m.velocity;
  assert.ok(previous > 0 && previous < 1);
  m.settle(0); assert.equal(m.position, previous); assert.equal(m.velocity, velocity);
  const grabbed = m.grab(); advance(); assert.equal(m.position, grabbed);
  m.drag(.6); assert.equal(frames.at(-1).p, .6); assert.equal(frames.at(-1).x, .6);
  m.drag(.3); assert.equal(frames.at(-1).p, .3);
  m.settle(0, { speed: -2 }); for (let i = 0; i < 80; i++) advance();
  assert.equal(m.position, 0); assert.equal(callback, null);
  m.settle(1, { instant: true }); assert.equal(m.position, 1); assert.equal(callback, null);
  m.settle(.5, { speed: -2 }); for (let i = 0; i < 80; i++) advance();
  assert.equal(m.position, .5, "automatic mode has its own stable middle stop");
  assert.ok(dragPosition(2) > 1 && dragPosition(2) < 1.04);
  assert.ok(dragPosition(-1) < 0 && dragPosition(-1) > -.04);
  m.settle(0); m.dispose(); assert.equal(callback, null);
});
