name: Unit tests
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.19.0'
          cache: npm
      - run: npm ci --ignore-scripts
      - run: node node_modules/electron/install.js
      - if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum npm test
      - if: runner.os == 'Windows'
        run: npm test
      - run: npm run build
